ashthespy/Atom-LaTeX

lib/builder.coffee, lib/config.coffee
Save all unsaved open files that belong to current document prior to build
Upon `Build`, check if any modified editor tabs belong to current document using `@latex.texFiles` from `@latex.manager.findAll()` and if the option is enabled, save the files before building.
Packages like [`atom-build`](https://github.com/noseglid/atom-build) has a confirmation dialog that pops up if the default setting is not set, however I think that might be bit obtrusive in a normal LaTeX workflow. What do you think?
=> Add `Save on Build`

lib/manager.coffee
Updating #35  to fix the case when you build using either the status bar or the package menu and not from the active editor pane.
=> Issue #31 - Fix when building from outside `ActiveTextEditor`

lib/autocomplete/citation.coffee, lib/autocomplete/command.coffee, lib/autocomplete/reference.coffee, lib/autocomplete/subFiles.coffee, lib/manager.coffee, package.json
Further to #41 - have implemented `chokidar` but a bit differently. 
The basic idea is that the entire `rootDir` is watched for files of interest that match common `tex` and `image` extensions, along with custom file extensions from the `.latexcfg` file 
Hence, there are multiple `chokidar.watch()` objects, one for the `rootDir` and one for the **each** `bibFile` found in the main tex file. 
On `change` events the watched file is parsed, and suggestions for references and command autocomplete is collected. 
On `add` and `unlink` events autocomplete file suggestions are added or removed for the corresponding file. 
Only `add` and `unlink` events are tracked for images, and autocomplete file suggestions are added or removed for the corresponding file. 
1.  When dependant files are be parsed …
=> Use `chokidar` to watch files and folders

lib/autocomplete/subFiles.coffee, lib/builder.coffee, lib/manager.coffee, lib/viewer.coffee, spec/main-spec.coffee
Combining a few things in this PR.
Have introduced a more robust attempt at multi-project support compared to the [initial implementation ](https://github.com/James-Yu/Atom-LaTeX/pull/47/files#diff-c9b4f199851474c585bd505761e0123dR8) 
This should reduce issues such as #45 
The `rootDir` is determined in the following hierarchy:
1. Use active editor if available.
1. Use the first open editor that has LaTeX grammar
1. Use first open Atom project - inform user via log
This should also implicitly address issues with the PDF viewer tabs like #63  and #64 as now the assumption that the active pane always is belongs to the main project is not made. 
Given #58, a minor tweak to keep tab of such metrics.
1. Folder watching can be disabled by setting a `disable_watcher` key to `true` under …
=> Multi-file handling improvements and minor tweaks

lib/autocomplete/syntax.coffee, lib/provider.coffee
Fixes two seemingly separate issues I am seeing on Atom 1.20.0-dev: (1) when you enter a dollar sign you get an error, (2) #82.
This switches the code to using proper getter functions instead, which seems to fix the problem.
=> Fix failures due to buffer.lines being undefined

lib/builder.coffee, lib/manager.coffee
As of now, the extension of the main file is stripped before compilation. Thus, `example.tex` will result in a command like `pdflatex example`.
This works fine for `.tex` files, as `pdflatex` will search for both `example` and `example.tex`. However it fails at custom extensions, like `.tikz`.
This commit removes the stripping of the main files extension. So, `example.tikz` would be passed to pdflatex as it is.
Related issue: https://github.com/James-Yu/Atom-LaTeX/issues/86
=> Stop stripping mainFiles extension before build

lib/manager.coffee
For those of us, who work with a lot of TikZ graphics, having multiple `.latexcfg`s to support the `.tikz` extension for every image in each folder can be quite a hassle.
This could be eased by looking for `.latexcfg` in a parent directory as in https://github.com/James-Yu/Atom-LaTeX/issues/72.
Otherwise, the common `.tikz` extension could be supported natively, as already I proposed in https://github.com/James-Yu/Atom-LaTeX/issues/86.
I know this is debatable, so feel free to consider this.
=> Regard .tikz files as TeX files as well

lib/autocomplete/citation.coffee, lib/builder.coffee, lib/manager.coffee
This PR combines two fixes (Unrelated but I pushed them all to the same repo - sorry!)
This should fix #80 
Have restructured the implantation of the `bibwatcher` (along the lines of LaTeX Workshop) that should now result in faster parsing and seamless switching between multiple open LaTeX projects.
This fixes #54 
Have tweaked the logging a bit to utilise more icons
=> Multiple small improvements 

lib/viewer.coffee, viewer/web/latex.js
Fix for #87 
1. What should the default behavior to open the link be?
a) <kbd>ctrl</kbd>+<kbd>Mouse Click</kbd>
b) <kbd>Mouse Click</kbd>
2. Is there a better event type to attach a listener to? 
The current implantation is attached to the `click` event - not the most elegant solution, but is the limit of my JS skills ;-)
=> Open external PDF links in default browser

README.md, lib/builder.coffee, lib/manager.coffee
Follow up from #89 and #90 that should provide a solution for #86 and #42
=> Add new '%EXT' placeholder for custom toolchains

lib/manager.coffee
Throw an error when an invalid `mainFile` is set, or e.g via magic commands. 
Should help in cases such as #99
=> Add error notification for invalid LaTeX root file

lib/manager.coffee
Fix for `fs.js` error messages when active editor is not of `tex` grammar.
`[(#102)](https://github.com/James-Yu/Atom-LaTeX/pull/102)  Fix root directory determination`
=> Fix root directory determination

lib/autocomplete/subFiles.coffee, lib/manager.coffee, lib/provider.coffee
Autocomplete `.bib` files in current project dir for `\addbibresource{}`
Also streamlined the `subFiles` provider code a bit.
Cheers!
`[(#98)](https://github.com/James-Yu/Atom-LaTeX/pull/98)  Add ``.bib`` to subfile-autocomplete + code clean up`
=> Add `.bib` to subfile-autocomplete 

lib/autocomplete/command.coffee
Fix #103 - Added recognition for `newcommand`. 
Implemented  from LaTeX-Workshop ;-)
```
`[(#104)](https://github.com/James-Yu/Atom-LaTeX/pull/104)  Add custom commands to autocomplete suggestions
```
=> Add custom commands to autocomplete suggestions

lib/builder.coffee
Should kill all child process when utilising latex builders such as `latexmk` or `arara`.
Tested on Windows, but needs some testing on MacOS and Unix.
Fixes #54
=> Kill all children process

spec/main-spec.coffee
Hello!
In Atom 1.23.0, the CoffeeScript dependency [will be upgraded from version 1.11.1 to 1.12.7](https://github.com/atom/atom/pull/13731). To ensure that all packages will remain working the same way, we searched for CoffeeScript compile output differences from all Atom packages and found your package to be affected by the update.
This pull request implements the fix mentioned in https://github.com/jashkenas/coffeescript/issues/4760#issuecomment-340001235, which is compatible with both versions.
Please let me know if you have any questions.
=> Changes required for upcoming CoffeeScript upgrade

lib/builder.coffee
Hello.
I find it useful to hide the notification when the "Show build log" button is pressed, since the full build log is going to appear in a new tab.
Thanks!
Philip
=> Dismiss Failure Notification when "Show build log" Is Pressed

README.md, lib/builder.coffee, lib/config.coffee, lib/manager.coffee, lib/viewer.coffee
Follow up from #211 
@maxb2 could you give this a shot? It should be more robust, while maintaining some flexibility still.
The logic is to strip known extensions, (`.tex` and `.tikz` by default along with ones defined in the `latex_ext` key) 
This should allow for such cases:
| Filename | `%DOC` | `%EXT` | `latex_ext`
| :---         |     :---:      |          :---: | :---: | 
| `foobar.tex` | `foobar` |`tex` | |
| `foo.bar.tex` | `foo.bar` |`tex` | |
| `foo.bar.tikz` | `foo.bar` |`tikz` | |
| `foobar.tex.tikz` | `foobar` |`tex.tikz` | `['tex.tikz']` | 
| `foo.bar.tex.tikz` | `foo.bar` |`tex.tikz` | `['tex.tikz']`|
Should be noted that when using `latex_ext` it should be expected to go in and change the build toolchain arguments to include `%EXT`
=> Filenames with dots

lib/config.coffee
Added space to separate the words "set" and "extensions" in the "Files to clean" section
=> Corrected missing space typo

lib/main.coffee, lib/manager.coffee, lib/view/panel.js, styles/atom-latex.less
- Automatically loading root path when opening a project
- Saving root path to .latexcfg when user is setting in manually
- Improved rendering of Latex panel
Slightly decreasing font-size
Path is overflowing to the left when it is too long
=> Root Path improvements
